# docs/openapi.yaml

openapi: 3.1.0
info:
  version: 1.0.0
  title: University of GOIT
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This is a documentation of University of GOIT
tags:
  - name: Students
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://127.0.0.1:8080
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
